import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import PreferenceModal from "@/components/modal/PreferenceModal";
import { ThemeProvider } from "@/components/theme-provider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const roboto = localFont({
  src: [
    {
      path: "../public/fonts/roboto/Roboto-Thin.ttf",
      weight: "300",
    },
    {
      path: "../public/fonts/roboto/Roboto-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/roboto/Roboto-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/roboto/Roboto-Bold.ttf",
      weight: "800",
    },
    {
      path: "../public/fonts/roboto/Roboto-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Schedule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressContentEditableWarning
        suppressHydrationWarning
        className={`font-roboto w-full h-screen p-0`}
      >
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster position="bottom-center" reverseOrder={false} />
            <PreferenceModal />
            {children}
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
